In [1]:
import numpy as np

In [8]:
arr = np.array([1,2,3,4.5,5])
arr

array([1. , 2. , 3. , 4.5, 5. ])

In [9]:
arr.shape

(5,)

In [10]:
arr.dtype

dtype('float64')

In [7]:
list_1D = [1,2,3,4.5,8]
list_1D

[1, 2, 3, 4.5, 8]

In [13]:
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
arr2D.shape
arr2D.dtype

dtype('int32')

In [15]:
arr2D.shape

(3, 3)

***List***
<br>리스트는 요소의 타입이 같지 않아도 된다.

In [16]:
arr3D = np.array([[[1],[2]],[[3],[4]],[[5],[6]],[[7],[8]]])
arr3D

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]],

       [[7],
        [8]]])

In [17]:
arr3D.shape

(4, 2, 1)

In [18]:
arr3D.dtype

dtype('int32')

In [19]:
arr3D = np.arange(24).reshape(4,3,2)
arr3D

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [20]:
arr_zero = np.zeros((2,3))
arr_zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
arr_one=  np.ones((3,3))
arr_one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
arr_one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
arr_linspace = np.linspace(1.,4.,5)
arr_linspace

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [27]:
arr1 = np.arange(4)
arr1

array([0, 1, 2, 3])

In [28]:
arr1 = arr1.reshape(2,2)
arr1

array([[0, 1],
       [2, 3]])

In [31]:
### Array 덧셈, 뺄셈, 곱셈, 나눗셈
arr1 = np.arange(4)
arr2 = np.arange(4)

In [32]:
arr1 + arr2

array([0, 2, 4, 6])

In [33]:
arr1 - arr2

array([0, 0, 0, 0])

In [34]:
arr1 * arr2

array([0, 1, 4, 9])

In [35]:
arr1 / arr2

array([nan,  1.,  1.,  1.])

# BroadCast

In [41]:
arr1 = arr1.reshape(2,2)

In [37]:
arr3 = np.array([2,2])
arr3

array([2, 2])

In [42]:
arr1 + arr3

array([[2, 3],
       [4, 5]])

In [43]:
arr1 * 2

array([[0, 2],
       [4, 6]])

In [45]:
arr1 **2

array([[0, 1],
       [4, 9]], dtype=int32)

# Index

In [46]:
arr4 = np.arange(10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr4[9]

9

In [48]:
arr4[3:7]

array([3, 4, 5, 6])

In [49]:
arr4_2D = np.array([[1,2,3],[4,5,6]])
arr4_2D

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
arr4_2D[0,2]

3

In [52]:
arr4_2D[:,2]

array([3, 6])

In [53]:
arr5 = np.array([True,False,True,False])
arr5

array([ True, False,  True, False])

In [56]:
vals = np.random.standard_normal(10)
vals

array([-0.53468614,  0.74890254, -0.3816593 ,  0.44994433, -2.39029203,
        1.74388507,  0.55059803, -0.83142456,  0.7146475 , -2.21453882])

In [68]:
arr6 = np.random.randint(10)
arr6

3