In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.2'

In [3]:
arr = np.arange(4)
arr.shape

(4,)

In [7]:
row_vec = arr[np.newaxis,:]
row_vec.shape
#row_vec

(1, 4)

In [5]:
col_vec = arr[:,np.newaxis]
col_vec.shape
#col_vec

(4, 1)

In [8]:
#2D - Array
x = np.array([1,2,3,4,5])
y = np.array([5,4,3])

In [12]:
x_new = x[:,np.newaxis]
x_new

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [14]:
y_new = y[np.newaxis,:]
y_new

array([[5, 4, 3]])

In [16]:
new = x_new + y_new
new

array([[ 6,  5,  4],
       [ 7,  6,  5],
       [ 8,  7,  6],
       [ 9,  8,  7],
       [10,  9,  8]])

In [17]:
new.shape

(5, 3)

In [22]:
# 3D - Array
arr = np.arange(25).reshape(5,5)
arr3D = arr[np.newaxis,...]
arr3D

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]])

In [24]:
arr3D.shape

(1, 5, 5)